import React, { useState, useEffect } from 'react';
import { formatDistanceToNow } from 'date-fns';
import { Star, Calendar, ExternalLink, Activity } from 'lucide-react';

const Discovery = () => {
  const [data, setData] = useState({ top: [], upcoming: [], news: [], lastUpdated: null });
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // In production, this fetches the static file generated by the GitHub Action
    fetch('./data/discovery.json')
      .then(res => res.json())
      .then(json => {
        setData(json);
        setLoading(false);
      })
      .catch(err => {
        console.error("Failed to load discovery data. Did the script run?", err);
        setLoading(false);
      });
  }, []);

  if (loading) {
    return (
      <div className="h-full flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-500"></div>
      </div>
    );
  }

  return (
    <div className="space-y-10">
      <header className="flex justify-between items-end mb-8">
        <div>
          <h2 className="text-3xl font-bold text-white mb-2">Anime Discovery</h2>
          <p className="text-gray-400">Discover trending and upcoming shows.</p>
        </div>
        {data.lastUpdated && (
          <div className="text-sm text-gray-500 flex items-center bg-gray-800 px-3 py-1.5 rounded-full border border-gray-700">
            <Activity size={14} className="mr-2 text-green-400" />
            Last updated: {formatDistanceToNow(new Date(data.lastUpdated), { addSuffix: true })}
          </div>
        )}
      </header>

      {/* Top Anime Section */}
      <section>
        <h3 className="text-2xl font-bold text-indigo-400 mb-6 flex items-center">
          <Star className="mr-2" /> Top Ranked Anime
        </h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-6">
          {data.top.slice(0, 5).map((anime) => (
            <a 
              key={anime.mal_id} 
              href={anime.url}
              target="_blank"
              rel="noopener noreferrer" 
              className="bg-gray-800 rounded-xl overflow-hidden shadow-lg border border-gray-700 hover:border-indigo-500 hover:-translate-y-1 transition-all group cursor-pointer flex flex-col"
            >
              <div className="relative h-64 overflow-hidden">
                <img 
                  src={anime.images.webp.large_image_url} 
                  alt={anime.title} 
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                />
                <div className="absolute top-0 right-0 bg-indigo-600 text-white font-bold px-3 py-1 m-2 rounded shadow">
                  #{anime.rank}
                </div>
              </div>
              <div className="p-4 flex-1 flex flex-col justify-between">
                <div>
                  <h4 className="font-bold text-gray-100 line-clamp-2 mb-2 group-hover:text-indigo-300">{anime.title}</h4>
                  <p className="text-xs text-gray-400 line-clamp-3">{anime.synopsis}</p>
                </div>
                <div className="mt-4 flex justify-between items-center text-sm">
                  <span className="flex items-center text-yellow-400"><Star size={14} className="mr-1 fill-current" /> {anime.score}</span>
                  <span className="text-gray-500">{anime.episodes || '?'} Eps</span>
                </div>
              </div>
            </a>
          ))}
        </div>
      </section>

      {/* Upcoming Anime Section */}
      <section>
        <h3 className="text-2xl font-bold text-purple-400 mb-6 flex items-center">
          <Calendar className="mr-2" /> Anticipated Upcoming
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {data.upcoming.slice(0, 4).map((anime) => (
            <div key={anime.mal_id} className="bg-gray-800 rounded-xl p-4 flex gap-4 border border-gray-700">
              <img 
                src={anime.images.webp.image_url} 
                alt={anime.title} 
                className="w-24 h-36 object-cover rounded shadow"
              />
              <div className="flex-1">
                <h4 className="font-bold text-lg text-gray-100 mb-1">{anime.title}</h4>
                <span className="inline-block bg-gray-700 text-xs px-2 py-1 rounded text-gray-300 mb-2">
                  {anime.season} {anime.year}
                </span>
                <p className="text-sm text-gray-400 line-clamp-3">{anime.synopsis || "No synopsis available yet."}</p>
                <a href={anime.url} target="_blank" rel="noopener noreferrer" className="mt-2 inline-flex items-center text-sm text-purple-400 hover:text-purple-300">
                  View on MAL <ExternalLink size={12} className="ml-1" />
                </a>
              </div>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
};

export default Discovery;